### ISSUE TITLE
Can you share the retrieval code for the fullwiki setting?

### ISSUE THREAD

**Issue by YeDeming** [hotpotqa/hotpot#20]
Hi,
Thanks for releasing the code, it's very helpful for me.

In paper's appendix, you introduce your retrieval strategy for fullwiki setting. I want to retrieve more than 10 articles, so I use DrQA's retriever(unigram+bigram hash table). But its performance is so far from the your results in the top 10 paragraphs.

Can you share the retrieval code for the fullwiki setting?

Thanks!

Best Regard,
Deming Ye

**Comment by qipeng** [comment]
Unfortunately the retrieval code is much too tied to the computation infrastructure we used to be shared easily, so we do not have a plan to share it publicly. But if you refer to the supplemental material of the paper, there are some tricks we used to speed things up in our implementation of the DrQA retriever. Alternatively, using an off-the-shelf retrieval system might also serve this purpose.
