### ISSUE TITLE
UnboundLocalError: local variable 'word_counter' referenced before assignment

### ISSUE THREAD

**Issue by wunaidev** [hotpotqa/hotpot#22]
`python main.py --mode prepro --data_file hotpot_train_v1.1.json --para_limit 2250 --data_split train`
`python main.py --mode prepro --data_file hotpot_dev_distractor_v1.json --para_limit 2250 --data_split dev`

[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done   1 tasks      | elapsed:    5.0s
[Parallel(n_jobs=12)]: Done   8 tasks      | elapsed:    6.4s
[Parallel(n_jobs=12)]: Done  17 tasks      | elapsed:    8.0s
......
[Parallel(n_jobs=12)]: Done 7057 tasks      | elapsed:  6.0min
[Parallel(n_jobs=12)]: Done 7176 tasks      | elapsed:  6.2min
[Parallel(n_jobs=12)]: Done 7297 tasks      | elapsed:  6.3min
[Parallel(n_jobs=12)]: Done 7405 out of 7405 | elapsed:  6.4min finished
7405 questions in total
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    prepro(config)
  File "/content/hotpot/prepro.py", line 324, in prepro
    word_emb_mat, word2idx_dict, idx2word_dict = get_embedding(word_counter, "word", emb_file=config.glove_word_file,
UnboundLocalError: local variable 'word_counter' referenced before assignment

**Comment by AndresFRJ98** [comment]
What was the fix on this? I also encountered this issue
