### ISSUE TITLE
Tensor split for start_output and end_output?

### ISSUE THREAD

**Issue by Vimos** [hotpotqa/hotpot#23]
I noticed that `start_output` uses the later half of `sp_output`
```
        start_output = torch.matmul(start_mapping.permute(0, 2, 1).contiguous(), sp_output[:,:,self.hidden:])
        end_output = torch.matmul(end_mapping.permute(0, 2, 1).contiguous(), sp_output[:,:,:self.hidden])
```
Is it OK to use the first half as `start_output`?

**Comment by qipeng** [comment]
This is us taking the state of the backward LSTM corresponding to the first token in the sentence as part of the input to predict supporting facts. You should feel free to use whatever feature you want in your extension. :)
