### ISSUE TITLE
A question about evaluating

### ISSUE THREAD

**Issue by tomtang110** [hotpotqa/hotpot#24]
Hi

I found you only provide the evaluating method for answer in your code. Could you provide the evaluating code for support facts? or joint evaluating method between ans and sup in order to make experiment better.

Kind regards
Tang

**Comment by qipeng** [comment]
The evaluation script in the repository contains all evaluation metrics we use. See: https://github.com/hotpotqa/hotpot/blob/master/hotpot_evaluate_v1.py
