### ISSUE TITLE
A question about evaluate.

### ISSUE THREAD

**Issue by tomtang110** [hotpotqa/hotpot#25]
Hi 
I run my results in the eval() in hotpot_evaluate_v1.py, however, the result may be not the same with your scores in leaderboard. Could you tell me the correct function to evaluate?
![屏幕快照 2019-07-07 14 35 18](https://user-images.githubusercontent.com/33299522/60764064-c58e9200-a0c4-11e9-9876-6238fd2bda0b.png)

**Comment by qipeng** [comment]
Hi, are you sure you're using our script on a complete output file (an example of predictions on the dev set can be found on the website)? Our script should print out a JSON object containing various metrics, and your output looks very different from it.
