### ISSUE TITLE
Unable to download the dataset from the website. 

### ISSUE THREAD

**Issue by pranavsinghal30** [hotpotqa/hotpot#34]
wget http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json shows "Network is Unreachable".
Even downloading the data set from https://hotpotqa.github.io/ shows unable to connect.

**Comment by qipeng** [comment]
Might be a temporary network issue -- it seems to be working for me right now. Could you try again?

**Comment by pranavsinghal30** [comment]
Hi,
I have tried downloading it again it's still not working for me.

**Comment by qipeng** [comment]
@pranavsinghal30 I can't seem to replicate the issue on my end (and my network is external to CMU as well). Are you able to access other CMU-based web content?
