### ISSUE TITLE
UnboundLocalError: local variable 'word_counter' referenced before assignment：during preprocessing

### ISSUE THREAD

**Issue by qizitong** [hotpotqa/hotpot#35]
when i want to give below command as per your manual at here..
Three commands have different errors
**python main.py --mode prepro --data_file hotpot_train_v1.1.json --para_limit 2250 --data_split train**
（
[Parallel(n_jobs=12)]: Done 35960 tasks      | elapsed:  2.4min
[Parallel(n_jobs=12)]: Done 36784 tasks      | elapsed:  2.5min
[Parallel(n_jobs=12)]: Done 37624 tasks      | elapsed:  2.5min
[Parallel(n_jobs=12)]: Done 38464 tasks      | elapsed:  2.5min
[Parallel(n_jobs=12)]: Done 39320 tasks      | elapsed:  2.6min
[Parallel(n_jobs=12)]: Done 40176 tasks      | elapsed:  2.6min
[Parallel(n_jobs=12)]: Done 41048 tasks      | elapsed:  2.7min
[Parallel(n_jobs=12)]: Done 41920 tasks      | elapsed:  2.7min
[Parallel(n_jobs=12)]: Done 42808 tasks      | elapsed:  2.8min
已杀死
）

**python main.py --mode prepro --data_file hotpot_dev_distractor_v1.json --para_limit 2250 --data_split dev**
（
[Parallel(n_jobs=12)]: Done 7405 out of 7405 | elapsed:   30.2s finished
7405 questions in total
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    prepro(config)
  File "/home/caoxing/project/hotpot-master/prepro.py", line 324, in prepro
    word_emb_mat, word2idx_dict, idx2word_dict = get_embedding(word_counter, "word", emb_file=config.glove_word_file,
UnboundLocalError: local variable 'word_counter' referenced before assignment
）

**python main.py --mode prepro --data_file hotpot_dev_fullwiki_v1.json --data_split dev --fullwiki --para_limit 2250**

（[Parallel(n_jobs=12)]: Done 7405 out of 7405 | elapsed:   30.3s finished
7405 questions in total
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    prepro(config)
  File "/home/caoxing/project/hotpot-master/prepro.py", line 324, in prepro
    word_emb_mat, word2idx_dict, idx2word_dict = get_embedding(word_counter, "word", emb_file=config.glove_word_file,
UnboundLocalError: local variable 'word_counter' referenced before assignment
）
I would be very appreciated if you can help me:)

**Comment by qipeng** [comment]
You're seeing the UnboundLocalError because you didn't finish processing the training set before starting to process the test set. Note that the process processing the training set failed. Try using fewer jobs to reduce RAM usage?

**Comment by qizitong** [comment]
Thank you for your reply. The problem has been solved.
