### ISSUE TITLE
DocQA or improved BiDAF?

### ISSUE THREAD

**Issue by valsworthen** [hotpotqa/hotpot#8]
Hello,

this may be a dumb question but from the code I have the feeling that the model looks more like BiDAF than [DocQA](https://arxiv.org/abs/1710.10723). DocQA is an improved BiDAF with a retrieval system to select a single paragraph on which to apply BiDAF. However if I'm not mistaken the preprocessing script joins all the Hotpot paragraph instead of selecting one. The only retrieval is in the creation of the fullwiki setup where 10 paragraphs are selected.

Sure the model contains improvements compared to BiDAF (self-attention, 3-way classifier, no highway layer) but not the main particularity of DocQA which is the retriever. Yet in the [paper](https://arxiv.org/pdf/1809.09600.pdf) states that the authors implemented DocQA. 

Can you confirm that the code indeed merges all the paragraphs?

Thanks.

**Comment by kimiyoung** [comment]
There are two stages. In the retrieval stage, we used bigram tfidf (which is also used in DrQA). In the comprehension stage, we concatenate all (retrieved) paragraphs and build a model to predict the answer.

**Comment by valsworthen** [comment]
Ok so if I understand, the retrieval stage is performed on all of wikipedia and returns the 10 paragraphs that are concatenated? 
There is no further retrieval performed on the 10 paragraphs per example given in the `train` and `dev_distractor` sets?

**Comment by kimiyoung** [comment]
Yes that's right. In terms of possible research directions, one might be interested in improving either the retrieval methods, the comprehension model, or a better pipeline.
